[package]
name = "tls"
version = "0.0.0"
workspace = "../../"
publish = false

[dependencies]
rocket = { path = "../../core/lib", features = ["tls"] }
rocket_codegen = { path = "../../core/codegen" }
