[package]
name = "managed_queue"
version = "0.0.0"
workspace = "../.."
publish = false

[dependencies]
crossbeam = "0.4"
rocket = { path = "../../core/lib" }
rocket_codegen = { path = "../../core/codegen" }
